### ISSUE TITLE
contracts/test/BasicOwnable.sol shouldn't need to exist

### ISSUE THREAD

**Issue by fiddlemath** [reserve-protocol/rsv-beta#11]
`Ownable` is not an abstract contract, so we shouldn't 'need a separate contract to trivially dervie from it as contracts/test/BasicOwnable.sol does.

So, we should either figure out why we _do_ want or need this testing contract, or just get rid of it.

**Comment by fiddlemath** [comment]
Quote:

> tbrent: I thought I tried to deploy an Ownable instance and couldn't, but looking at it now I can't see how that would be the case. We should be able to remove BasicOwnable.

**Comment by tbrent** [comment]
Doing this.

**Comment by tbrent** [comment]
Huh. It seems to be the case that since `Ownable` has an internal constructor (which the solidity documentation says is ok!) the go bindings don't contain a `DeployOwnable` method like they normally would. I guess this was the blocker I was vaguely recalling. 

Closing this, feel free to reopen if it's worth pursuing more.
